<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Bas Kamer Me')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css') ?>
</head>
<body>
<div id="bg">
    <div id="img">
        <img src="/img/me.jpg" alt="It's Me!">
    </div>
</div>
<div id="content">
    <div id="container">
        <?php echo $this->content; ?>
    </div>
</div>

<?php echo $this->inlineScript() ?>
</body>
</html>
