<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Bas Kamer Me')->setSeparator(' - ')->setAutoEscape(false) ?>

    <link href='http://fonts.googleapis.com/css?family=Raleway:100' rel='stylesheet' type='text/css'>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=0.5')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/jquery-1.10.2.min.js')
        ->appendFile($this->basePath() . '/js/jquery.fitimage.js')
        ->appendFile($this->basePath() . '/js/main.js'); ?>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css') ?>
</head>
<body>

    <img src="/img/me.jpg" class="fitimage" data-scale-mode="outside" data-min-width="640" alt="It's Me!" >


<div id="content">
    <div id="container">
        <?php echo $this->content; ?>
    </div>
</div>

<?php echo $this->inlineScript() ?>
</body>
</html>
